---
site_name: HTAN Phase 2 Data Model
site_description: HTAN Phase 2 Data Model Documentation
site_author: HTAN Consortium

theme:
  name: material
  palette:
    - scheme: default
      primary: red
      accent: amber

plugins:
  - search

nav:
  - Home: index.md
  - Clinical: clinical.md
  - Biospecimen: biospecimen.md
  - Core File: corefile.md
  - Sequencing: sequencing.md
  - WES: wes.md
  - scRNA-seq: scrna-seq.md
  - Imaging: imaging.md
  - Digital Pathology: digitalpathology.md
  - Multiplex Microscopy: multiplexmicroscopy.md
  - Spatial Omics: spatialomics.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - tables
