---
site_name: HTAN Phase 2 Data Model
site_description: HTAN Phase 2 Data Model Documentation
site_author: HTAN Consortium

theme:
  name: material
  palette:
    - scheme: default
      primary: red
      accent: amber

plugins:
  - search

nav:
  - Home: index.md
  - Clinical: clinical/index.md
  - Biospecimen: biospecimen/index.md
  - Core File: corefile/index.md
  - Sequencing: sequencing/index.md
  - WES: wes/index.md
  - scRNA-seq: scrna-seq/index.md
  - Imaging: imaging/index.md
  - Digital Pathology: digitalpathology/index.md
  - Multiplex Microscopy: multiplexmicroscopy/index.md
  - Spatial Omics: spatialomics/index.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - tables
