#!/usr/bin/env python3
"""
Build modules/Clinical/domains/uberon_tissues.yaml from an Uberon release
(issue #198). The YAML is a build artifact and is not committed: it is
generated from Uberon at build / release time, and the Uberon release it was
built from is recorded in the schema header (`version:` and `source:`).

Release selection, in priority order:
    --release YYYY-MM-DD
    $UBERON_RELEASE
    the latest release on https://github.com/obophenotype/uberon/releases

Uberon cuts a release roughly quarterly, so a data model release built today
picks up the current Uberon release and is pinned to it from then on.

Filtering:
    - only UBERON-prefixed [Term] stanzas
    - drop terms marked `is_obsolete: true`
    - drop terms with `never_in_taxon` pointing at Homo sapiens or any of its
      ancestors, and propagate that exclusion down is_a / part_of to children
      (e.g. "feather" is never_in Euarchontoglires, so "down feather" goes too)

When the output YAML already exists, the script prints which codes were added
and removed, including the `replaced_by` / `consider` targets for codes that
went obsolete, so reviewers can check whether submitted data uses a dropped
code.

Usage:
    # Build from the latest Uberon release (overwrites any existing YAML)
    python3 scripts/build_uberon_enum.py

    # Only build if the YAML is missing (used by make / pytest / docs builds)
    python3 scripts/build_uberon_enum.py --if-missing

    # Specific release, or a locally-cached OBO file
    python3 scripts/build_uberon_enum.py --release 2026-06-23
    python3 scripts/build_uberon_enum.py --obo-file /path/to/uberon-basic.obo

Pass `--keep-non-human` to skip the taxon filter.
"""
import argparse
import os
import re
import time
import urllib.request
from collections import defaultdict
from pathlib import Path

LATEST_URL = "https://github.com/obophenotype/uberon/releases/latest"
RELEASE_URL = (
    "https://github.com/obophenotype/uberon/releases/download/"
    "v{release}/uberon-basic.obo"
)
DEFAULT_OUTPUT = (
    Path(__file__).resolve().parent.parent
    / "modules/Clinical/domains/uberon_tissues.yaml"
)

# NCBITaxon lineage of Homo sapiens (NCBI Taxonomy, efetch id=9606)
HUMAN_LINEAGE = {
    f"NCBITaxon:{t}"
    for t in (
        1,
        131567,
        2759,
        33154,
        33208,
        6072,
        33213,
        33511,
        7711,
        89593,
        7742,
        7776,
        117570,
        117571,
        8287,
        1338369,
        32523,
        32524,
        40674,
        32525,
        9347,
        1437010,
        314146,
        9443,
        376913,
        314293,
        9526,
        314295,
        9604,
        207598,
        9605,
        9606,
    )
}

HEADER = """\
# GENERATED by scripts/build_uberon_enum.py from Uberon release {release}.
# Do not edit or commit; re-run the script to rebuild.
id: https://w3id.org/htan/uberon_tissues
name: uberon_tissues
description: UBERON codes for tissues and organs (Uberon release {release}, non-obsolete terms applicable to Homo sapiens)
title: UBERON Tissue and Organ Codes
version: "{release}"
source: {url}
enums:
  tissue_or_organ_of_origin_uberon_enum:
    name: tissue_or_organ_of_origin_uberon_enum
    description: UBERON codes for tissues and organs of origin (Uberon release {release})
    permissible_values:
"""

CODE_RE = re.compile(r"^      (UBERON:\d+):$")
RELEASE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}$")


def escape_yaml_double_quoted(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def _open(url: str, attempts: int = 3):
    req = urllib.request.Request(
        url, headers={"User-Agent": "htan2-data-model-build-uberon-enum/1.0"}
    )
    for i in range(attempts):
        try:
            return urllib.request.urlopen(req, timeout=120)
        except OSError:
            if i == attempts - 1:
                raise
            time.sleep(5 * (i + 1))


def resolve_latest_release() -> str:
    """Follow the GitHub /releases/latest redirect to get the tag date."""
    with _open(LATEST_URL) as resp:
        tag = resp.geturl().rstrip("/").rsplit("/", 1)[-1]
    release = tag.lstrip("v")
    if not RELEASE_RE.match(release):
        raise SystemExit(f"Could not parse Uberon release from {resp.geturl()}")
    return release


def fetch_obo_text(release: str) -> str:
    url = RELEASE_URL.format(release=release)
    print(f"Downloading {url}")
    with _open(url) as resp:
        return resp.read().decode("utf-8")


def parse_terms(text: str) -> dict:
    """Return {id: {tag: [values]}} for every UBERON [Term] stanza."""
    terms = {}
    cur = None
    for line in text.splitlines():
        if line.startswith("["):
            cur = defaultdict(list) if line == "[Term]" else None
            continue
        if cur is None or ": " not in line:
            continue
        tag, value = line.split(": ", 1)
        cur[tag].append(value)
        if tag == "id" and value.startswith("UBERON:"):
            terms[value] = cur
    return terms


def _target(value: str) -> str:
    """'part_of UBERON:0000001 ! foo' -> 'UBERON:0000001'; 'UBERON:x ! foo' -> 'UBERON:x'."""
    return value.split(" ! ")[0].split()[-1]


def non_human_terms(terms: dict) -> set:
    """Terms with a never_in_taxon constraint covering humans, plus all descendants."""
    children = defaultdict(set)
    seeds = set()
    for tid, tags in terms.items():
        for parent in tags.get("is_a", []):
            children[_target(parent)].add(tid)
        for rel in tags.get("relationship", []):
            parts = rel.split()
            if parts[0] == "part_of":
                children[parts[1]].add(tid)
            elif parts[0] == "never_in_taxon" and parts[1] in HUMAN_LINEAGE:
                seeds.add(tid)
    excluded = set()
    stack = list(seeds)
    while stack:
        tid = stack.pop()
        if tid in excluded:
            continue
        excluded.add(tid)
        stack.extend(children.get(tid, ()))
    return excluded


def select_terms(terms: dict, keep_non_human: bool) -> dict:
    """Return {code: name} for terms that belong in the enum."""
    obsolete = {t for t, tags in terms.items() if tags.get("is_obsolete") == ["true"]}
    excluded = set() if keep_non_human else non_human_terms(terms)
    print(
        f"  {len(terms)} UBERON terms, {len(obsolete)} obsolete, "
        f"{len(excluded - obsolete)} excluded as never in Homo sapiens"
    )
    return {
        tid: tags["name"][0]
        for tid, tags in terms.items()
        if tid not in obsolete and tid not in excluded and tags.get("name")
    }


def existing_codes(path: Path) -> set:
    if not path.exists():
        return set()
    with path.open(encoding="utf-8") as fh:
        return {m.group(1) for line in fh if (m := CODE_RE.match(line.rstrip("\n")))}


def report_diff(old: set, new: dict, terms: dict) -> None:
    if not old:
        return
    added = sorted(set(new) - old)
    removed = sorted(old - set(new))
    print(f"  +{len(added)} added, -{len(removed)} removed vs existing YAML")
    for code in removed:
        tags = terms.get(code)
        if tags is None:
            reason = "not in this release"
        elif tags.get("is_obsolete") == ["true"]:
            repl = tags.get("replaced_by", []) + tags.get("consider", [])
            reason = "obsolete" + (f" -> {', '.join(repl)}" if repl else "")
        else:
            reason = "never in Homo sapiens"
        name = tags["name"][0] if tags and tags.get("name") else ""
        print(f"    - {code}  {name}  ({reason})")


def write_enum(codes: dict, output: Path, release: str, url: str) -> int:
    # Write to a temp file first so an interrupted build never leaves a
    # truncated YAML behind for --if-missing to accept.
    tmp = output.with_suffix(output.suffix + ".tmp")
    with tmp.open("w", encoding="utf-8") as fh:
        fh.write(HEADER.format(release=release, url=url))
        for code in sorted(codes):
            fh.write(f"      {code}:\n")
            fh.write(
                f'        description: "{escape_yaml_double_quoted(codes[code])}"\n'
            )
    tmp.replace(output)
    return len(codes)


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument(
        "--release",
        default=os.environ.get("UBERON_RELEASE") or None,
        help="Uberon release date tag, e.g. 2026-10-01 "
        "(default: $UBERON_RELEASE, else the latest GitHub release)",
    )
    ap.add_argument(
        "--obo-file",
        type=Path,
        help="Path to a locally-cached uberon-basic.obo. "
        "If omitted, it is downloaded from the GitHub release.",
    )
    ap.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    ap.add_argument(
        "--if-missing",
        action="store_true",
        help="Do nothing if the output YAML already exists",
    )
    ap.add_argument(
        "--keep-non-human",
        action="store_true",
        help="Do not drop terms with a never_in_taxon constraint covering humans",
    )
    args = ap.parse_args()

    if args.if_missing and args.output.exists():
        return

    if args.obo_file:
        text = args.obo_file.read_text(encoding="utf-8")
    else:
        if not args.release:
            args.release = resolve_latest_release()
            print(f"Latest Uberon release: {args.release}")
        text = fetch_obo_text(args.release)

    # The GitHub release tag identifies the release. The OBO data-version can
    # lag the tag by a few days (v2026-06-23 ships data-version 2026-06-19), so
    # it is only used when building from a local file with no --release.
    m = re.search(r"^data-version: uberon/releases/([\d-]+)/", text, re.M)
    if not m:
        raise SystemExit("OBO file has no Uberon data-version header")
    release = args.release or m.group(1)

    terms = parse_terms(text)
    codes = select_terms(terms, args.keep_non_human)
    report_diff(existing_codes(args.output), codes, terms)
    url = RELEASE_URL.format(release=release)
    n = write_enum(codes, args.output, release, url)
    print(f"Wrote {n} permissible values (Uberon {release}) to {args.output}")


if __name__ == "__main__":
    main()
