# Built from:
# https://docs.github.com/en/actions/guides/building-and-testing-python
---
name: Build and test htan2-data-model

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        run: |
          python -m pip install --user poetry
          export PATH="$HOME/.local/bin:$PATH"
          poetry --version

      - name: Install dependencies
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          poetry install --no-interaction --no-root

      - name: Install project
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          poetry install --no-interaction

      - name: Run test suite
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          make test
